/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package petstoregradleproject;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class Library {
	public boolean someLibraryMethod() {
		return true;
	}

	public static void main(String[] args) {
		@SuppressWarnings("resource")
		ApplicationContext context = new ClassPathXmlApplicationContext("springbean.xml");

		Person person = context.getBean("person", Person.class);
		System.out.println(person.getPersonName());
		System.out.println(person.getAge());
		System.out.println();

		Account account = context.getBean("account", Account.class);
		System.out.println(account.getEmail());
		System.out.println(account.getPerson().getPersonName());
		System.out.println(account.getPerson().getAge());
		System.out.println();

		Payment payment = context.getBean("payment", Payment.class);
		System.out.println(payment.getAmount());
		System.out.println(payment.getPerson().getPersonName());
		System.out.println(payment.getPerson().getAge());
		System.out.println();
		System.out.println(payment.getPerson1().getPersonName());
		System.out.println(payment.getPerson1().getAge());
		System.out.println();

		@SuppressWarnings("resource")
		ApplicationContext context2 = new AnnotationConfigApplicationContext(ApplicationConfiguration.class);

		Person person3 = context2.getBean("person", Person.class);
		System.out.println(person3.getPersonName());
		System.out.println(person3.getAge());
		System.out.println();

		@SuppressWarnings("resource")
		AnnotationConfigApplicationContext context3 = new AnnotationConfigApplicationContext();
		context3.scan("PetStoreGradleProject");
		context3.refresh();
		Person person4 = context3.getBean("person", Person.class);
		System.out.println(person4.getPersonName());
		System.out.println(person4.getAge());
	}
}